version: '3'

services:
  container_sample:
    container_name: container-sample-api
    image: container-sample:v1.0
    ports:
        - 5000:5000
    environment:
        - "ASPNETCORE_URLS=http://+:5000"
